- name: ghcr.io/dgtlmoon/changedetection.io:latest
  labels:
    diun.provider: cmejule06002d23rifj8w7liq
- name: dgtlmoon/sockpuppetbrowser:latest
  labels:
    diun.provider: cmejulice002e23ri5hlt1nor
- name: freshrss/freshrss:latest
  labels:
    diun.provider: cmejumh1w002j23rid7xgb1r4
- name: danielszabo99/microbin:latest
  labels:
    diun.provider: cmejukaty002623ribagbt5qd
- name: ghcr.io/nezhahq/nezha:latest
  labels:
    diun.provider: cmejumlw0002k23ric3a6unex
- name: jc21/nginx-proxy-manager:latest
  labels:
    diun.provider: cmejulanb002c23ricyqm83kq
- name: xream/sub-store:latest
  labels:
    diun.provider: cmejul25k002a23riykdmvqao
- name: victoriametrics/vmagent:latest
  labels:
    diun.provider: cmejukxll002923ri3lnmb14p
- name: prom/blackbox-exporter:latest
  labels:
    diun.provider: cmejul5wz002b23ris6dldcx3
- name: prom/node-exporter:latest
  labels:
    diun.provider: cmejumqcg002l23ri8wcjf1jr
- name: bellamy/wallos:latest
  labels:
    diun.provider: cmejukf2x002723ri414hl54a
- name: snowdreamtech/frps:latest
  labels:
    diun.provider: cmejukit7002823rimsbqi0xp
- name: ddsderek/wxchat:latest
  labels:
    diun.provider: cmejum100002f23riz3e7v1k7
- name: neilforest/subconverter-frontend:latest
  labels:
    diun.provider: cmejum5qy002g23ri662ww08k
- name: tindy2013/subconverter:latest
  labels:
    diun.provider: cmejum977002h23ri6vz3ucnm
- name: corentinth/it-tools:latest
  labels:
    diun.provider: cmejumdbx002i23ri489suvz9
