- name: registry.cn-guangzhou.aliyuncs.com/fnapp/trim-chromium:latest
  labels:
    diun.provider: cmen884ma00539pkdgo5r5gyb
- name: lscr.io/linuxserver/transmission:4.0.5
  labels:
    diun.provider: cmen8837900519pkdvn5uvxiw
- name: victoriametrics/vmagent:latest
  labels:
    diun.provider: cmen87yvn004v9pkdr5634w6z
- name: prom/blackbox-exporter:latest
  labels:
    diun.provider: cmen880aq004x9pkd8lc57eep
- name: prom/node-exporter:latest
  labels:
    diun.provider: cmen881sy004z9pkdlph4y5um
- name: ghcr.io/snowdreamtech/frpc:latest
  labels:
    diun.provider: cmen87xel004t9pkdzuq5d9be
