- name: jc21/nginx-proxy-manager:latest
  labels:
    diun.provider: cmelpj3ag0048e8di5vetat9p
- name: ghcr.io/snailyp/gemini-balance:latest
  labels:
    diun.provider: cmelpfkye003se8diktuunta5
- name: grafana/grafana:latest
  labels:
    diun.provider: cmelpju0t004ce8dius249yxk
- name: victoriametrics/victoria-metrics:latest
  labels:
    diun.provider: cmelpk8if004ee8dibbwio72u
- name: mysql:8
  labels:
    diun.provider: cmelpfysd003ue8difwh2ppsp
- name: prom/blackbox-exporter:latest
  labels:
    diun.provider: cmelph9gg0040e8did1wlzqla
- name: jc21/mariadb-aria:latest
  labels:
    diun.provider: cmelpjgmd004ae8dixlhqum3b
- name: postgres:16
  labels:
    diun.provider: cmelpi1bf0044e8di1iep9jj2
- name: victoriametrics/vmagent:latest
  labels:
    diun.provider: cmelpgfgp003we8dijol6o7lh
- name: prom/node-exporter:latest
  labels:
    diun.provider: cmelpguv6003ye8die3qmadkn
- name: docker.n8n.io/n8nio/n8n:latest
  labels:
    diun.provider: cmelphmsy0042e8diixar507d
- name: hunsh/gh-proxy-py:latest
  labels:
    diun.provider: cmelpiprp0046e8di20kcc12v
