- name: prom/blackbox-exporter:latest
  labels:
    diun.provider: cmexzkvzb02vzue4evpry6rta
- name: mysql:8
  labels:
    diun.provider: cmexzkvz602vtue4edx5orpqf
- name: jc21/nginx-proxy-manager:latest
  labels:
    diun.provider: cmexzkvzf02w7ue4eh2mifxc6
- name: grafana/grafana:latest
  labels:
    diun.provider: cmexzkvzh02wbue4e1m8a2zhq
- name: docker.n8n.io/n8nio/n8n:latest
  labels:
    diun.provider: cmexzkvzc02w1ue4er4uinoaj
- name: victoriametrics/victoria-metrics:latest
  labels:
    diun.provider: cmexzkvzi02wdue4ezw66o90t
- name: ghcr.io/snailyp/gemini-balance:latest
  labels:
    diun.provider: cmexzkvz502vrue4ejqsci0ws
- name: prom/node-exporter:latest
  labels:
    diun.provider: cmexzkvza02vxue4eu5s5j4od
- name: hunsh/gh-proxy-py:latest
  labels:
    diun.provider: cmexzkvze02w5ue4ewnkiksu1
- name: jc21/mariadb-aria:latest
  labels:
    diun.provider: cmexzkvzg02w9ue4eguisaec9
- name: victoriametrics/vmagent:latest
  labels:
    diun.provider: cmexzkvz802vvue4ewy36yx6h
- name: postgres:16
  labels:
    diun.provider: cmexzkvzd02w3ue4er7oxcoy2
